security: 
  basic: 
    enabled: false

management: 
  security: 
    enabled: false

spring: 
  jpa: 
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate: 
      ddl-auto: update
 
greetingLanguage: English
---
spring: 
  profiles: dev
greetingLanguage: French
---
spring: 
  profiles: prod
greetingLanguage: Spanish
    